### ISSUE TITLE
mapsto

### ISSUE THREAD

**Issue by performantdata** [winitzki/sofp#12]
You use → (U+2192) in 1.1.2 to mean "maps to", but ↦ (U+21a6) is actually used in math to mean that. It's `\mapsto` in LaTeX.

**Comment by performantdata** [comment]
Also, shouldn't you call it an "anonymous" function, instead of "nameless", since that's what Scala calls it?

**Comment by performantdata** [comment]
Also, shouldn't you call it an "anonymous" function, instead of "nameless", since that's what Scala calls it? I see that you make a connection in section 1.7.7, but I haven't heard the term "nameless" used elsewhere, though I'm not well-versed on this matter. Where is this term coming from?

**Comment by winitzki** [comment]
1. Yes, of course \mapsto is not the same as \rightarrow. One possibility would be to use \rightarrow for types but \mapsto for values.  I just don't want to use more symbols than necessary. Scala uses `=>` both for types and for values. The distinction between \mapsto and \rightarrow does not help.

2. I call it "nameless" because it doesn't have a name. "Anonymous" means we don't know its name. Yes, most people say "anonymous function" but I think it's not very helpful.
