### ISSUE TITLE
Font size very small

### ISSUE THREAD

**Issue by jmgimeno** [winitzki/sofp#56]
I wonder whether it would be possible to create a version of the PDF with bigger fonts. Even when reading it in landscape orientation on my iPad the letter is very small.

**Comment by winitzki** [comment]
Increasing the font size means reformatting the whole book and rewriting all code examples and all equations in the later chapters. For chapters 1-3 this could be possible because there aren't yet any equations. Then the book will be about 1200 pages long instead of about 800 pages as it is now.

I am considering to split the book into two volumes (with chapters 1-5 in the first volume). Then the first volume could be published with larger fonts indeed.

**Comment by jmgimeno** [comment]
Ok, I understand. Thanks.
