### ISSUE TITLE
A few typos in Chapter 6, on functors

### ISSUE THREAD

**Issue by allenjhan** [winitzki/sofp#61]
On pp172 of the March 5, 2022 edition,

We have the following equation: "c.fmap(f).fmap(g) == c.fmap(f andThen g) == c.fmap(x => g(f(x)))"

What is probably meant is the following: " "c.map(f).map(g) == c.map(f andThen g) == c.map(x => g(f(x)))"

So "fmap" should be replaced with "map."

On pp194 of the March 5, 2022 edition,

We have the following start of a sentence: "For any functtion f of type A → B,"

Note that function is spelled incorrectly here.

**Comment by winitzki** [comment]
Thank you. I will correct this in the next release.

The spelling error in `functtion` is especially worrying because I have a spellchecking script and it did not catch that error.

**Comment by winitzki** [comment]
@allenjhan I have found the bug in the spellchecking script and corrected a few spelling errors that I could not find until now. Thank you!

**Comment by allenjhan** [comment]
You're welcome!

**Comment by allenjhan** [comment]
These comments are for the March 5, 2022 edition.

On page 217, I had trouble understanding one aspect of the table for "compute; get." It was that the symbol 1 was the value for a type of Unit. To my knowledge, this is the first time in the text that the symbol 1 is used to denote a value of type Unit. This was never explicitly stated in the text early on when the Unit type was introduced, so at first I did not understand this notation. It was only after thinking about it that I understood what was intended.

On page 225, I had a question about the notation avg[T: Fractional]. When does this notation refer to a context bound - that is, when we are calling an implicit of type Fractional[T] - and when does this notation simply mean T is of type Fractional?

Although I am currently using the March 5, 2022 edition as the basis for my comments, the hard copy I am using to read the text is the December 29, 2021 edition. At least in this edition, there is one aspect of the discussion in the book that I find unsatisfactory. I do not have a page number for this comment, but in the discussion for contravariance, it is not clear to me why nesting type parameters in the contravariant position of a type flips the type from contravariant to covariant and back again. It does not seem obvious to me why this is the case, so some demonstration of why this happens would help my intuition. Also, I do want to say that the discussion of contravariance and subtyping is excellent, and after reading this book I have an understanding of why some data types are contravariant and not covariant, and the intuition behind contramap.

On page 361, the definition of final case class Writer is missing a closing brace after the definition of flatMap.

On page 479, there is one case of the word separate spelled as "seoarate." You mentioned that you fixed the spell checker for the book, so this mistake may already be corrected in your branch.

I was not able to go over every single expression in the book line-by-line as I originally intended. I am still trying to get used to the notation, and am still struggling with certain constructions, like recursive type definitions. However, the book has richly repaid the effort I have put into it, and I am certain it will repay further study going forward.

**Comment by winitzki** [comment]
Thank you for your comments. Please do not hesitate to let me know if something is not clear. For example, what do you feel is unclear about recursive type definitions?

> the symbol 1 is used to denote a value of type Unit. 

Yes, that's a problem if the book never defines this symbol before using it. I will revise some of the text in earlier chapters to make this clear. The type Unit is denoted by a "blackboard bold 1" symbol ($\mathbb{1}$), and the value of type Unit is denoted by 1. In many cases I write a function as `_ -> x` when the argument is of type Unit because the argument may be ignored. I hope this is also explained somewhere in the book.

> notation avg[T: Fractional]. When does this notation refer to a context bound - that is, when we are calling an implicit of type Fractional[T] - and when does this notation simply mean T is of type Fractional?

The notation [T: Fractional] can only refer to type parameters because of the square brackets. A value T of type Fractional will be in round parentheses. 

```scala
def func(T: Fractional)  // value argument T of type Fractional. Usually, value arguments are not capitalized, but Scala will accept this too.
def func[T: Fractional](x: T)  // type parameter T with typeclass constraint Fractional, and a value argument x of type T
```

**Comment by winitzki** [comment]
Actually, Section 7.1.1. defines the notation for the Unit type and value (in the section "Use a constant"). 

> All named unit values are denoted by 1 and are viewed as having type 𝟙.

**Comment by allenjhan** [comment]
> For example, what do you feel is unclear about recursive type definitions?

It is hard for me to say exactly. Whenever I have run into proofs involving recursive type definitions in this book, I have made a mental note to skip the derivation and return to it later, since a quick inspection of the material made me feel that I would have to invest more time than I was willing to spend right now to understand it thoroughly. I think it is just something I need to spend more time to master and that there is nothing particularly confusing about the presentation in the book.

> I will add a clarification to indicate what properties are proved where. The results are summarized in Table 6.2 (page 198) and Table 6.4 (page 205). This is discussed at the beginning of Section 6.2.5. Did you find that discussion confusing?

No, I thought this part of the book was very clear. It was just that one detail that I had a question about.

**Comment by winitzki** [comment]
Maybe what is unclear to you about covariance of $(A \rightarrow B) \rightarrow B$ is that this question is equivalent to the question of why `F[G[A]]` is covariant when both `F[X]` and `G[X]` are contravariant functors?

**Comment by winitzki** [comment]
As for the recursive proofs, let me ask you this. Take a simple recursive definition of `List[A]` and a simple recursive definition of `fmap` for `List`:

```scala
sealed trait List[A]
final case class Nil[A]() extends List[A]
final case class Cons[A](head: A, tail: List[A]) extends List[A]

def fmap[A, B](f: A => B): List[A] => List[B] = {
  case Nil()                     => Nil()
  case Cons(head, tail)   => Cons(f(head), fmap(f)(tail))
}
```

I am intentionally using a definition that is very straightforward, but not stack safe and not efficient, because it's the easiest one to use for proofs.

How would you prove that `fmap(id) == id`?

**Comment by allenjhan** [comment]
> Maybe what is unclear to you about covariance of (A→B)→B is that this question is _equivalent_ to the question of why `F[G[A]]` is covariant when both `F[X]` and `G[X]` are contravariant functors?

Yes, I think my issue was that I did not know how to translate the statement of the problem into a proposition that could be proved. Writing it that way does clarify the problem to be solved for me.

> You would apply `fmap(id)(x)` to an arbitrary list value `x: List[A]`. You need to show that the result of evaluating `fmap(id)(x)` is equal to `x`. How would you proceed?

I am not sure if this is what you are looking for, but it is a question of showing that `fmap(id) == id`. It is clear that in the definition of fmap that you provided, if the input list is Nil, our equation is satisfied. So it remains to show that `Cons(f(head), fmap(f)(tail))` does not alter the list ​when `f == id`.

I spent some time just now flipping through the book and thinking about the problem on my own.  I didn't find  anything thing in the book that could make the argument in a rigorous fashion, but that is probably because I don't know where to look. The only thing I could think of was to make a sort of argument by induction, using the case of a single element list as a base case. If we know that fmap(id)(x) returns x for a single element list, then we can say fmap(id)(x) returns x for an n-element list if n > 1, by induction.

That is because we can always start with the expression `case Cons(head, tail) => Cons(f(head), fmap(f)(tail))` to show that the head of the list is always unchanged by applying id. That is the base case. The induction step is to show that the segment of the list that remains will also have a head that is unchanged. So the induction step proceeds by starting from the fact that if the head of the list always remains unchanged, and then showing that the second element of the list (because it is also a head of a list) will also be unchanged. If that is the case, since we have both a base case and an induction step, we have shown the formula applies for a list of arbitrary length n.

**Comment by winitzki** [comment]
I will add a bit more clarification to Section 6.2.5 and explain why Statement 6.2.3.5 is relevant.

As for the inductive proof of `fmap(id) == id` for `List`, you are on the right track, proving by induction that each element of the list remains unchanged (the head, then the second element, and so on) when `fmap(id)` is applied.

I would make the argument a bit simpler:

The base case is the empty list (a list of length 0). This is easy to prove since we just see `Nil = Nil`, as you already said.

The induction step is to show that `fmap(id) == id` when applied to a list of length `n + 1`, assuming that we already proved that `fmap(id) == id`  for all lists of length `n` (the _inductive assumption_). So, we need to show that `Cons(id(head), fmap(id)(tail))`  is equal to `Cons(head, tail)` where `tail` is a list of length `n`. Clearly `id(head) = head`. It remains to show that `fmap(id)(tail) == tail`. But `tail` is a list of length `n`, for which we already proved that `fmap(id) == id`. So, we get `fmap(id)(tail) == id(tail) == tail`.

This is how I would prove the identity law of `fmap` for `List`.

Notice that the inductive assumption is applied to the recursive call of `fmap` inside its body. This is the standard pattern: whenever we prove a property of a recursive function, we use induction and the inductive assumption is that the property already holds for all recursive calls.

Now, I actually looked over Chapters 3 and 6 and I also did not find a proof of `fmap` laws for `List` anywhere. For some reason I thought I already wrote it up somewhere but apparently I did not.  I think this proof is important enough to write out explicitly. I will add one more "solved example" in Chapter 6 to prove that `fmap` for `List` satisfies the functor laws. This will give me an opportunity to explain how inductive proofs are used when you want to prove some property of a recursive function.

Right now Chapter 6 proves the `fmap` laws for all recursively defined functors at once. This is done in Statement 6.2.3.7 and its proof is not easy to understand especially if you are still not sure about how to do inductive proofs for laws. 

I am convinced now that this presentation is insufficient, and I will add at least one page with full derivations and explanations for the `List` `fmap` and perhaps some other examples and exercises.

**Comment by allenjhan** [comment]
After reading your comments, I see I did not get the proof quite right. As you say, the idea of the inductive step should be to start with the list xs and assume that fmap(id)(xs) == xs (the inductive assumption) in order to show that for the n+1 case that fmap(id)(x::xs) == x::xs is true. That can be demonstrated by substituting x::xs into the definition of fmap and showing the result when f == id is equal to x::xs.

**Comment by winitzki** [comment]
@allenjhan I am going to add 2 more pages to Chapter 6, showing in detail the full proof of the laws of `fmap` for the `List` functor. I am attaching these pages as PDF to this comment, feel free to take a look. I hope this will be helpful. 
[new_list_functor.pdf](https://github.com/winitzki/sofp/files/8940608/new_list_functor.pdf)

**Comment by allenjhan** [comment]
I see. Thank you. I am sure this new material will be as helpful for new readers as our discussion was for me.
